name: Production
on:
  push:
    tags: ["*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ~1.14.0
      - run: |
          TAG=$(git describe --tags --abbrev=0 HEAD)
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          RELEASE_NOTES=$(git log "$LAST_TAG..HEAD" --oneline --decorate)

          go get -u github.com/tcnksm/ghr
          ghr -b "${RELEASE_NOTES}" -t "${{ secrets.GITHUB_TOKEN }}" -u "${GITHUB_REPOSITORY%%/*}" -recreate "${TAG}"

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - uses: ./.github/actions/docker-build-deploy
        with:
          skip_deploy: true
          docker_registry: quay.io
